### ISSUE TITLE
How to build it?

### ISSUE THREAD

**Issue by vkhv** [bem-contrib/react-xjst#9]
Hi, thank for your work!

How i can build this example?

```
var reactXjst = require('react-xjst');
var React = require('react');
var ReactDOM = require('react-dom');
var templates = require('./templates'); // bundle with templates and bem-xjst compiler

var provide = reactXjst(templates, React);

function MyComponent() {
    return provide({
        block: 'my-block'
    });
}

ReactDOM.render(React.createElement(MyComponent), document.getElementById('root'));
```

I used webpack

```
webpack this-example.js bundle.js
```

But got error:

```
ERROR in ./~/bem-xjst/index.js
Module not found: Error: Cannot resolve module 'fs' in C:\Users\khvostov\test\cc-exp\node_modules\bem-xjst
 @ ./~/bem-xjst/index.js 1:9-22
```

Because bem-xjst using fs module. Did you faced with this error? Do you have any ideas how it can fix? Or suggest another way to get working example in browser?

**Comment by Guria** [comment]
webpack resolve mechanism could be very tricky. try to add:
```js
resolve: {
    fallback: path.join(__dirname, 'node_modules')
}
```
to your webpack config object

**Comment by Guria** [comment]
You should have pre-generated `templates.js` file with `bem-xjst`. `bem-xjst` shouldn't be called in your client code. BTW, I don't see a `require('bem-xjst')` in provided example. Can you show your templates.js?

**Comment by vkhv** [comment]
Nothing special, just copied example, which required bem-xjst

```
$ cat templates/index.js
var bemxjst = require('bem-xjst');
var bemhtml = bemxjst.bemhtml;

// Add templates
var templates = bemhtml.compile(function() {
  block('b').content()('yay');
});

// Apply templates to data context in BEMJSON format and get result as HTML string
templates.apply({ block: 'b' });
// Result: <div class="b">yay</div>
```

**Comment by Guria** [comment]
@vladkhvo we don't have official support of `vidom` engine in `bem-xjst` yet until bem/bem-xjst#235 will be merged. So you will have to clone a fork, build it and generate a bundle with templates using `vidom` engine.

**Comment by vladkhvo** [comment]
Can you say how to do pre-generate? =)

**Comment by Guria** [comment]
it's a bit tricky at the moment. you can see https://github.com/awinogradov/react-bl/blob/master/webpack.config.js but it is not much trivial

**Comment by vkhv** [comment]
Thank you!

**Comment by Guria** [comment]
in a few words:
- get `bem-xjst` fork from @awinogradov 
- generate templates using `vidom` engine:

``` js
var fs = require('fs')
var bemxjst = require('bem-xjst');

fs.writeFileSync('./templates.js', bemxjst.vidom.generate(function() {
  block('b').content()('yay');
}))
```

**Comment by awinogradov** [comment]
@Guria @vladkhvo it's not necessary to compile by hands. Bundles compiles after bem-xjst install by npm script. You can find templates compiling process here https://github.com/awinogradov/react-bl/blob/master/webpack.config.js#L27-L53

**Comment by awinogradov** [comment]
@vladkhvo close issue if you find answer ;)

**Comment by vkhv** [comment]
Thx!
